config/routes.rb
Rails.application.routes.draw do

  root 'clowns#index'

  resources :clowns, only: [:index, :show]
  resources :bookings, only: [:create]

end

app/models/clown.rb
class Clown < ActiveRecord::Base
  include RankingData

  CONTRACTS = [:fulltime, :parttime, :student]

  has_many :bookings

  validates :name, presence: true
  validates :contract, presence: true

  def has_appointment?(date, time)
    Booking.where(appointment_date: date, appointment_time: time, clown: self).count > 0
  end

  # [LSP] This method is not a correct substitute for RankingData module.
  # RankingData#ranking_data returns Ranking object when bookings.empty? method returns false which is Boolean
  # Therefore a condition was implemented in the view: /app/views/clowns/show.html.erb
  #
  # Change this method to be a proper substitute for RankingData#ranking_data
  #   - Use NullObject pattern (https://en.wikipedia.org/wiki/Null_Object_pattern)
  #     when bookings are empty: rules, if a clown is a student he has 10 points (RankingNoBooking is the NullObject)
  #   - Remove the condition from views: clowns/show.html.erb
  #   - Make sure the rspec tests are green
  def ranking_data
    bookings.empty? ? false : super
  end

  # Duplicate code:
  # Use method missing or class eval to apply meta programming
  # ----------------------------------------------------------
  # self.instance_eval do
  #   Clown::CONTRACTS.each do |available_contract|
  #     method_name = "is_#{available_contract}?"
  #     define_method method_name.to_sym do
  #       contract.to_sym == available_contract
  #     end
  #   end
  # end

  def is_student?
    contract.to_sym == :student
  end

  def is_fulltime?
    contract.to_sym == :fulltime
  end

  def is_parttime?
    contract.to_sym == :parttime
  end
end

app/models/presentation/clown.rb
class Presentation::Clown
  attr_accessor :last_booking

  def initialize(clown)
  end
end

app/controllers/clowns_controller.rb
class ClownsController < ApplicationController
  def index
    @clowns = Clown.all
  end

  def show
    begin
      @clown = Clown.find params[:id]
      @booking = Booking.new clown: @clown
    rescue ActiveRecord::RecordNotFound
      flash[:warning] = 'Clown was not found'
      redirect_to clowns_path
    end
  end
end

app/helpers/clowns_helper.rb
module ClownsHelper
end

app/views/clowns/index.html.erb
<h1 class="cover-heading">Choose the best clown for your party</h1>

<div class="clowns-index">
<% @clowns.each do |clown| %>
    <a href="<%= clown_path clown %>" >
      <img src="<%= clown.image %>" alt="<%= clown.name %>" class="img-circle <%= clown.contract %>"
           data-toggle="tooltip" data-placement="bottom" title="<%= clown.name %>" />
    </a>
<% end %>
</div>

<script type="text/javascript">
</script>

app/views/clowns/show.html.erb
<img src="<%= @clown.image %>" class="img-circle circle-l" alt="<%= @clown.name %>">

<h1>
  <%= @clown.name %>
</h1>

<% if @clown.is_student? %>
<p>
    <span class="label label-info">student</span>
</p>
<% end %>


<% # [LOD] Demeter Law is violated here. %>
<% # We can fix the problem using Decorator pattern and delegates %>
<% # Check the Presentation::Clown object. %>
<% # It should decorate a clown object and delegate missing methods to decorated class %>
<% # Use the Presentation::Clown.last_booking instead of chain of calls inside the template %>
<% # https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding %>
<% unless @clown.bookings.empty? %>
    <p>Last booking was on <%= @clown.bookings.last.created_at.strftime('%e.%-m.%Y') %></p>
<% end %>

<% # [LSP] Remove the conditions once Clown#ranking_data is fixed %>

<p>Points <span class="badge"><%= @clown.ranking_data.points %></p>
<p>Bookings <span class="badge"><%= @clown.ranking_data.bookings %></p>

<span class="separator"></span>

<h3>Book this clown</h3>

<%= simple_form_for @booking do |f| %>
    <%= f.input :appointment_date %>
    <%= f.input :appointment_time, as: :select, collection: Booking::APPOINTMENT_TIME %>
    <%= f.input :clown_id, as: :hidden %>
    <%= f.submit 'Book', {class: 'btn btn-default'} %>
<% end %>